version: '3.8'

services:
  postgres:
    container_name: whe_postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    volumes:
      - ./strapidata:/var/lib/postgresql/data
    ports:
      - 5432:5432
