export const postResponseMock: StrapiDataItem<PostResponseEntity> = {
  id: 1,
  attributes: {
    title: 'Test Post',
    summary: 'This is a test post',
    content: '{"time":123456789,"version":"","blocks":[]}',
    locale: 'en',
    imgUrl: 'https://example.com/test.png',
    createdAt: '2022-04-01T00:00:00.000Z',
    updatedAt: '2022-04-01T00:00:00.000Z',
    publishedAt: '2022-04-01T00:00:00.000Z',
    categories: {
      data: [
        {
          id: 1,
          attributes: {
            code: 'test-category',
            main: true,
            name: 'Test Category',
            description: 'This is a test category',
            createdAt: '2022-04-01T00:00:00.000Z',
            updatedAt: '2022-04-01T00:00:00.000Z',
          },
        },
      ],
    },
    coverImage: {
      data: {
        id: 1,
        attributes: {
          name: 'test image',
          alternativeText: 'test alt text',
          caption: 'test caption',
          width: 1000,
          height: 500,
          formats: {
            small: {
              ext: 'jpg',
              url: '/media/small_test.jpg',
              hash: 'testhash',
              mime: 'image/jpeg',
              name: 'small_test',
              path: null,
              size: 100,
              width: 500,
              height: 250,
              provider_metadata: {
                public_id: 'public-id',
                resource_type: 'type',
              },
            },
            medium: {
              ext: 'jpg',
              url: '/media/medium_test.jpg',
              hash: 'testhash',
              mime: 'image/jpeg',
              name: 'medium_test',
              path: null,
              size: 200,
              width: 750,
              height: 375,
              provider_metadata: {
                public_id: 'public-id',
                resource_type: 'type',
              },
            },
            large: {
              ext: 'jpg',
              url: '/media/large_test.jpg',
              hash: 'testhash',
              mime: 'image/jpeg',
              name: 'large_test',
              path: null,
              size: 400,
              width: 1000,
              height: 675,
              provider_metadata: {
                public_id: 'public-id',
                resource_type: 'type',
              },
            },
            thumbnail: {
              ext: 'jpg',
              url: '/media/thumbnail_test.jpg',
              hash: 'testhash',
              mime: 'image/jpeg',
              name: 'thumbnail_test',
              path: null,
              size: 10,
              width: 15,
              height: 25,
              provider_metadata: {
                public_id: 'public-id',
                resource_type: 'type',
              },
            },
          },
          hash: 'testhash',
          ext: 'jpg',
          mime: 'image/jpeg',
          size: 300,
          url: '/media/test.jpg',
          previewUrl: null,
          provider: 'provider',
          provider_metadata: {
            public_id: 'public-id',
            resource_type: 'type',
          },
          createdAt: '2022-04-01T12:00:00.000Z',
          updatedAt: '2022-04-01T12:00:00.000Z',
        },
      },
    },
    coverImageAuthor: null,
    coverImageSourceUrl: null,
    localizations: undefined,
    writer: {
      data: {
        id: 1,
        attributes: {
          name: 'Test Writer',
          createdAt: '2022-04-01T00:00:00.000Z',
          updatedAt: '2022-04-01T00:00:00.000Z',
          avatar: 'https://example.com/test-avatar.png',
          twitter: 'testwriter',
          personalUrl: 'https://example.com/test-writer',
        },
      },
    },
  },
}

export const postMock: Post = {
  categories: [
    {
      code: 'test-category',
      createdAt: '2022-04-01T00:00:00.000Z',
      description: 'This is a test category',
      id: 1,
      localizedName: 'Test Category',
      main: true,
      name: 'Test Category',
      updatedAt: '2022-04-01T00:00:00.000Z',
    },
  ],
  content: {
    blocks: [],
    time: 123456789,
    version: '',
  },
  coverImage: {
    alternativeText: 'test alt text',
    caption: 'test caption',
    createdAt: '2022-04-01T12:00:00.000Z',
    ext: 'jpg',
    formats: {
      large: {
        ext: 'jpg',
        hash: 'testhash',
        height: 675,
        mime: 'image/jpeg',
        name: 'large_test',
        path: null,
        size: 400,
        url: '/media/large_test.jpg',
        width: 1000,
      },
      medium: {
        ext: 'jpg',
        hash: 'testhash',
        height: 375,
        mime: 'image/jpeg',
        name: 'medium_test',
        path: null,
        size: 200,
        url: '/media/medium_test.jpg',
        width: 750,
      },
      small: {
        ext: 'jpg',
        hash: 'testhash',
        height: 250,
        mime: 'image/jpeg',
        name: 'small_test',
        path: null,
        size: 100,
        url: '/media/small_test.jpg',
        width: 500,
      },
      thumbnail: {
        ext: 'jpg',
        hash: 'testhash',
        height: 25,
        mime: 'image/jpeg',
        name: 'thumbnail_test',
        path: null,
        size: 10,
        url: '/media/thumbnail_test.jpg',
        width: 15,
      },
    },
    hash: 'testhash',
    height: 500,
    id: 1,
    mime: 'image/jpeg',
    name: 'test image',
    previewUrl: null,
    provider: 'provider',
    size: 300,
    updatedAt: '2022-04-01T12:00:00.000Z',
    url: '/media/test.jpg',
    width: 1000,
  },
  coverImageAuthor: null,
  coverImageSourceUrl: null,
  createdAt: '2022-04-01T00:00:00.000Z',
  id: 1,
  imgUrl: 'https://example.com/test.png',
  locale: 'en',
  localizations: null,
  publishedAt: '2022-04-01T00:00:00.000Z',
  summary: 'This is a test post',
  title: 'Test Post',
  updatedAt: '2022-04-01T00:00:00.000Z',
  writer: {
    avatar: 'https://example.com/test-avatar.png',
    createdAt: '2022-04-01T00:00:00.000Z',
    id: 1,
    name: 'Test Writer',
    personalUrl: 'https://example.com/test-writer',
    twitter: 'testwriter',
    updatedAt: '2022-04-01T00:00:00.000Z',
  },
}
