export { getAbout } from './about'
export { getCategories } from './category'
export { mediaResponseEntity } from './media'
export { addComment, addCommentValidate, getComments } from './comment'
export { getLatestPosts, getPostById, getAlgoliaPosts, postResponseMock } from './post'
