export { GlobalStyles } from './GlobalStyles/GlobalStyles'
export { NavLink } from './NavLink/NavLink'
export { WheFooter } from './WheFooter/WheFooter'
export { WheHeader } from './WheHeader/WheHeader'
export { HeaderImage } from './home'
