# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - '**'

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  build:
    runs-on: ubuntu-latest
    environment: preview
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      API_URL: ${{ secrets.API_URL }}
      NEXTJS_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH }}
      NEXTJS_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      NEXTJS_SENTRY_LOG_LEVEL: ${{ secrets.SENTRY_LOG_LEVEL }}
      NEXTJS_SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      NEXTJS_SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      NEXTJS_SENTRY_RELEASE: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn
      - run: yarn build
  
