# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: preview
    env:
      API_URL: ${{ secrets.API_URL }}
      NEXTJS_SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH }}
      NEXTJS_SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      NEXTJS_SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_AUTH: ${{ secrets.SENTRY_AUTH }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_LOG_LEVEL: ${{ secrets.SENTRY_LOG_LEVEL }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_RELEASE: ${{ github.sha }}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@1.2.0
        with:
          token: ${{ secrets.SENTRY_AUTH }}
          organization: ${{ secrets.SENTRY_ORG }}
          project: ${{ secrets.SENTRY_PROJECT }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn build
